// FFmpeg Integration Helper
// Note: FFmpeg cannot run directly in Chrome extension due to browser limitations
// This module provides instructions and helpers for FFmpeg conversion

export class FFmpegHelper {
  constructor() {
    this.conversionInstructions = {
      hls: {
        title: 'Convert HLS to MP4',
        command: 'ffmpeg -i "input.m3u8" -c copy output.mp4',
        description: 'Converts HLS stream to MP4 without re-encoding'
      },
      dash: {
        title: 'Convert DASH to MP4',
        command: 'ffmpeg -i "input.mpd" -c copy output.mp4',
        description: 'Converts DASH stream to MP4 without re-encoding'
      },
      merge: {
        title: 'Merge Video and Audio',
        command: 'ffmpeg -i video.mp4 -i audio.m4a -c copy output.mp4',
        description: 'Merges separate video and audio tracks'
      }
    };
  }
  
  getConversionInstructions(videoType) {
    return this.conversionInstructions[videoType] || null;
  }
  
  generateConversionCommand(videoType, inputFile, outputFile = 'output.mp4') {
    const instructions = this.conversionInstructions[videoType];
    if (!instructions) {
      return null;
    }
    
    return instructions.command
      .replace('input.m3u8', inputFile)
      .replace('input.mpd', inputFile)
      .replace('output.mp4', outputFile);
  }
  
  async showConversionGuide(videoType, filename) {
    const instructions = this.getConversionInstructions(videoType);
    if (!instructions) {
      return;
    }
    
    const command = this.generateConversionCommand(videoType, filename);
    
    // Create a guide file
    const guideContent = `
# Video Conversion Guide

## File: ${filename}
## Type: ${videoType.toUpperCase()}

### Requirements
- FFmpeg installed on your system
- Download link: https://ffmpeg.org/download.html

### Conversion Command

\`\`\`bash
${command}
\`\`\`

### Step-by-Step Instructions

1. Install FFmpeg if not already installed
   - Windows: Download from https://ffmpeg.org/download.html
   - macOS: brew install ffmpeg
   - Linux: sudo apt install ffmpeg

2. Open terminal/command prompt

3. Navigate to the folder containing the downloaded file
   \`\`\`bash
   cd Downloads
   \`\`\`

4. Run the conversion command
   \`\`\`bash
   ${command}
   \`\`\`

5. Wait for conversion to complete

6. Your MP4 file will be ready: output.mp4

### Alternative Tools

- **yt-dlp**: pip install yt-dlp
- **VLC Media Player**: Can convert using GUI
- **HandBrake**: GUI-based video converter

### Troubleshooting

- If command fails, try: \`ffmpeg -i "${filename}" -c:v libx264 -c:a aac output.mp4\`
- For high quality: \`ffmpeg -i "${filename}" -c:v libx264 -crf 18 -c:a aac -b:a 192k output.mp4\`
- For smaller file size: \`ffmpeg -i "${filename}" -c:v libx264 -crf 28 -c:a aac -b:a 128k output.mp4\`

---
Generated by Video Download Helper Pro
`;
    
    // Create blob and download guide
    const blob = new Blob([guideContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    
    await chrome.downloads.download({
      url: url,
      filename: `conversion-guide-${Date.now()}.md`,
      saveAs: false
    });
    
    // Show notification
    chrome.notifications.create({
      type: 'basic',
      iconUrl: 'icons/icon128.png',
      title: 'Conversion Guide Downloaded',
      message: 'Check your downloads folder for conversion instructions'
    });
  }
  
  // Web-based conversion using ffmpeg.wasm (future implementation)
  async convertInBrowser(videoBlob, options = {}) {
    // This would require ffmpeg.wasm library
    // For now, we'll just show a message
    throw new Error('Browser-based conversion not yet implemented. Please use FFmpeg command-line tool.');
  }
  
  // Generate streaming URL for external tools
  generateStreamingUrl(manifestUrl, quality = 'best') {
    return {
      url: manifestUrl,
      ytdlp: `yt-dlp -f ${quality} "${manifestUrl}"`,
      streamlink: `streamlink "${manifestUrl}" ${quality}`,
      ffmpeg: `ffmpeg -i "${manifestUrl}" -c copy output.mp4`
    };
  }
}
